// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFRRE7yt_Mzt8q10X9IGqTVj2S1QrCuM',
    appId: '1:942576278680:web:1b43f4a0a42bc66bdf04ed',
    messagingSenderId: '942576278680',
    projectId: 'scanner-app-e1c6d',
    authDomain: 'scanner-app-e1c6d.firebaseapp.com',
    storageBucket: 'scanner-app-e1c6d.firebasestorage.app',
    measurementId: 'G-EM4W49MX93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3BpOYqTICeyqBodhLUEHGms5uSUDyDGE',
    appId: '1:942576278680:android:aab87ca87d106c6adf04ed',
    messagingSenderId: '942576278680',
    projectId: 'scanner-app-e1c6d',
    storageBucket: 'scanner-app-e1c6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD07W-axoa1xFrH8zDACdcM1MMZqBDwi0',
    appId: '1:942576278680:ios:7f6af306f325ac60df04ed',
    messagingSenderId: '942576278680',
    projectId: 'scanner-app-e1c6d',
    storageBucket: 'scanner-app-e1c6d.firebasestorage.app',
    iosBundleId: 'com.example.scannQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD07W-axoa1xFrH8zDACdcM1MMZqBDwi0',
    appId: '1:942576278680:ios:7f6af306f325ac60df04ed',
    messagingSenderId: '942576278680',
    projectId: 'scanner-app-e1c6d',
    storageBucket: 'scanner-app-e1c6d.firebasestorage.app',
    iosBundleId: 'com.example.scannQrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFRRE7yt_Mzt8q10X9IGqTVj2S1QrCuM',
    appId: '1:942576278680:web:0b9e2432fb3a2c5bdf04ed',
    messagingSenderId: '942576278680',
    projectId: 'scanner-app-e1c6d',
    authDomain: 'scanner-app-e1c6d.firebaseapp.com',
    storageBucket: 'scanner-app-e1c6d.firebasestorage.app',
    measurementId: 'G-CV9QH4Y95Z',
  );
}
